
"""
FLUX Runtime Framework Protocol
"""


#   BUILT-IN IMPORTS
from typing import Protocol


#   PROTOCOL
class Flux(Protocol):
    """ FLUX runtime framework class protocol """
    def dev_mode(self) -> bool: ...
    def active(self) -> bool: ...
    def is_alive(self) -> bool: ...
    def in_startup(self) -> bool: ...
    def startup_time(self) -> float: ...
    def has_fatal_error(self) -> bool: ...
    def services_enabled(self) -> bool: ...
    def base_service(self) -> dict: ...
    def service(self, requestor, root: bool = False) -> dict: ...
    def is_rfw_manager(self, obj) -> bool: ...
    @staticmethod
    def is_rfw() -> bool: ...
    def set_main_window(self, window, start: bool = False) -> None: ...
    def add_window(self, identifier: str, cls: type, **kwargs) -> None: ...
    def inject_service(self, call: str, cls: type, func, clearance: int = 0) -> None: ...
    def run_application(self) -> None: ...
    def framework_exit(self) -> None: ...
