
"""
FLUX Runtime Framework View Module Protocol
"""


#   BUILT-IN IMPORTS
from typing import Protocol
from .fwp import Flux


#   PROTOCOL
class FwV(Protocol):
    """ FLUX runtime framework view module protocol """
    def __init__(self, hfw: Flux, cls: type, uid: str, parent: any = None, **kwargs) -> None: ...
    def view_type(self) -> str: ...
    def identifier(self) -> str: ...
    def uclient(self) -> any: ...
    def properties(self) -> any: ...
    def views(self) -> any: ...
    def event(self) -> any: ...
    def present(self, view: str) -> None: ...
    def hide(self) -> None: ...
    def show(self) -> None: ...
    def take_focus(self) -> None: ...
    def bind(self, event, func, add: str = None): ...

    # Framework module based
    def hfw(self) -> Flux: ...
    def fwm_class(self) -> type: ...
    def fwm_name(self) -> str: ...
    def hfw_service(self, svc: str, **svc_args) -> any: ...
    def console(self, msg: str, error: bool = False, **kwargs) -> None: ...

    # Tkinter based
    def winfo_width(self): ...
    def winfo_height(self): ...
    def winfo_rootx(self): ...
    def winfo_rooty(self): ...
    def config(self, **kwargs): ...
    def geometry(self, param): ...
